name: release

on:
  push:
    tags:
      - v*

jobs:
  test-pack-release:
    runs-on: ubuntu-latest
    name: Test, Pack and Release
    steps:
      - name: Configure environment
        id: config
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e "s/^refs\/tags\/v//")
          echo ::set-output name=version::$VERSION
      - name: Fetch repository
        uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          exec: sed -i "s/0.1.0/${{steps.config.outputs.version}}/g" Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Create a pre-release
        id: pre_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.config.outputs.version }}"
          prerelease: true
          title: "Pre-release ${{ steps.config.outputs.version }}"
          files: |
            LICENSE
            target/release/biominer-indexd
      - name: Output
        run: echo "${{steps.pre_release.outputs.automatic_releases_tag}}"